-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    date_id integer NOT NULL,
    year integer NOT NULL,
    month smallint NOT NULL,
    monthname character varying(20)[] NOT NULL,
    dayofmonth smallint NOT NULL,
    dayofweek smallint NOT NULL,
    dayofweekname character varying(20) NOT NULL,
    PRIMARY KEY (date_id)
);

CREATE TABLE public."softcartDimCategory"
(
    category_id integer NOT NULL,
    category character varying(100)[] NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE public."softcartDimItem"
(
    item_id integer NOT NULL,
    item character varying(150)[] NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE public."softcartDimCountry"
(
    country_id integer NOT NULL,
    country character varying(50)[] NOT NULL,
    PRIMARY KEY (country_id)
);

CREATE TABLE public."softcartFactSales"
(
    order_id integer NOT NULL,
    item_id integer NOT NULL,
    category_id integer NOT NULL,
    price double precision NOT NULL,
    country_id integer NOT NULL,
    date_id integer NOT NULL,
    PRIMARY KEY (order_id)
);

ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (date_id)
    REFERENCES public."softcartDimDate" (date_id)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartDimItem" (item_id)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (category_id)
    REFERENCES public."softcartDimCategory" (category_id)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."softcartDimCountry" (country_id)
    NOT VALID;

END;